### ISSUE TITLE
请问是否可以提供化学有机环状物数据集的label呢

### ISSUE THREAD

**Issue by Rechargeablezz** [Septemberxin/Chemical-Datasets#1]
请问是否可以提供化学有机环状物数据集的label？

**Comment by Septemberxin** [comment]
已更新数据集链接

**Comment by Rechargeablezz** [comment]
非常感谢，有劳您了
祝好！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Septemberxin ***@***.***>
发送时间: Wednesday, May 31, 2023 8:54:07 PM
收件人: Septemberxin/Offline-Handwritten-Chemical-Notations-Datasets ***@***.***>
抄送: Rechargeablezz ***@***.***>; Author ***@***.***>
主题: Re: [Septemberxin/Offline-Handwritten-Chemical-Notations-Datasets] 请问是否可以提供化学有机环状物数据集的label呢 (Issue #1)


已更新数据集链接

―

**Comment by Rechargeablezz** [comment]
> 已更新数据集链接

请问是否有化合物对应的表达式标签（例如SMILES）呢，还是只有目前下载链接中的ring/chain/...级别的标签呢

**Comment by Septemberxin** [comment]
只有目前下载链接中的ring/chain/...级别的标签
